display list item names
the-collab-lab/tcl-60-smart-shopping-list pull request #14
Opened 2023-04-06 07:05 UTC by labrocadabro

Co-author-by: jtooba70@gmail.com

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2023-04-06 07:32 UTC, labrocadabro commented
We opted for name={item.name} to pass the name, as it's more aligned with the specific requirements of this PR, but I'm curious what mentors think of using {...item}? It doesn't change the visible outcome and still meets all the AC, but does prepare for known future changes that will need to be made. 

Interested in it from a best practice point of view - do you keep scope as limited as possible? I know you shouldn't write code to prepare for *unknown* future changes, but what about *known* ones? Do you commit code that you know will need to be replaced later, or let the scope of the solution expand slightly?

2023-04-06 17:18 UTC, shahx95 commented
Great job @labrocadabro @ToobaJamal ! The changes look good to me. Thanks! 🤗

2023-04-06 17:21 UTC, shahx95 commented
Since it wasn't mentioned in the acceptance criteria, I was wondering if it might be possible for the mentors to let us know if we should consider adding a unique "key" prop to each ListItem component in the future?

2023-04-06 17:30 UTC, ToobaJamal commented
> 

Ah yes, good question. Might also be an obvious thing.
@paramsiddharth, @RajGM your thoughts?

2023-04-07 02:01 UTC, labrocadabro commented
Oh right!  Personally I'd lean towards adding another commit to the PR that adds the key, since we're getting a console warning about the issue.

2023-04-08 05:28 UTC, paramsiddharth commented
> We opted for name={item.name} to pass the name, as it's more aligned with the specific requirements of this PR, but I'm curious what mentors think of using {...item}? It doesn't change the visible outcome and still meets all the AC, but does prepare for known future changes that will need to be made.

I am all in for it — The only point to note here is that the `item's properties shouldn't collide with other HTML or component props!

> Interested in it from a best practice point of view - do you keep scope as limited as possible? I know you shouldn't write code to prepare for _unknown_ future changes, but what about _known_ ones? Do you commit code that you know will need to be replaced later, or let the scope of the solution expand slightly?

It's more than Schrödinger's cat when we speak of good practices, let me explain:
1. In most situations, keeping the scope as limited as possible is recommended. Why? Because most importantly, we want all props to be evidently visible so that we _know_ what we're sending in if it ever breaks in future.
2. Keeping the scope limited, both in Python's named arguments and React's props, comes at a cost of repetition. Nobody wants to write `prop1={prop1} prop2={prop2} prop3={prop3} prop4={prop4} prop5={prop5}...`. There's a limit to how much we focus on the scope being evident. Until that limit is crossed, we keep it explicit.
3. When that limit is crossed, however, we weigh towards modifying the data model to align with the needs of the component, and not the other way round. In that situation, the priority changes to keep the data model (here, `item`) tightly in line with the component's needs, and there we can simply go with `{...item}`.
4. In extremely simple and non-changing situations, we can omit overthinking and simply follow whatever suits us. :)

2023-04-08 05:32 UTC, paramsiddharth commented
> Since it wasn't mentioned in the acceptance criteria, I was wondering if it might be possible for the mentors to let us know if we should consider adding a unique "key" prop to each ListItem component in the future?

> Ah yes, good question. Might also be an obvious thing. @paramsiddharth, @RajGM your thoughts?

> Oh right! Personally I'd lean towards adding another commit to the PR that adds the key, since we're getting a console warning about the issue.

As Shah said, I'd highly recommend having that in the PR! It's not about the acceptance criteria, more about React's requirements. In most situations it would just work without adding a key attribute, but that doesn't mean we shouldn't.

@labrocadabro @ToobaJamal Let's aim to have that change done before we merge the PR in today's sync.

2023-04-08 05:34 UTC, paramsiddharth requested changes

2023-04-08 05:34 UTC, paramsiddharth commented on src/views/List.jsx
> +				))}
Please add a `key` attribute to the `ListItem` component. You can use the index as the key.

2023-04-08 05:37 UTC, labrocadabro commented
@ToobaJamal This is an extremely simple change and I'm a bit busy this morning so can you take care of this yourself?

2023-04-08 06:37 UTC, ToobaJamal commented on src/views/List.jsx
> +				))}
Done that. Please check the changes now :)

2023-04-08 06:57 UTC, paramsiddharth approved these changes
Excellent work! :)

2023-04-08 06:59 UTC, shahx95 approved these changes
Looks good to me! :)

2023-04-08 07:10 UTC, merged