Allow users to create new lists
the-collab-lab/tcl-60-smart-shopping-list pull request #16
Opened 2023-04-09 07:22 UTC by labrocadabro

## Description

**TBD**

## Related Issue

Closes #3 

## Acceptance Criteria

- @the-collab-lab/shopping-list-utils is added as a dependency to the project.
- The string my test list in App.jsx is replaced with null, so users are not automatically subscribed to any list.

If a user doesn’t already have a token:
- A button in the Home component allows them to create a new list
- Clicking the button generates a new token and saves it to localStorage using the setListToken function in App.jsx.
- Once the token has been created and saved, the user is redirected to the List view.
If a user does already have a token:
- They are automatically redirected to the List view.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![Home page before changes](https://user-images.githubusercontent.com/5794319/230759887-b4e0f06e-1860-4652-9cfe-4b2036e80e67.png)

### After

## Testing Steps / QA Criteria

**TBD**

2023-04-12 15:32 UTC, ToobaJamal approved these changes
I have tested the changes locally and its working as expected :)

2023-04-14 13:49 UTC, shahx95 commented on src/App.jsx
> +	}, [listToken, setListToken]);
The setListToken dependency does not seem necessary in this case. Just having listToken will suffice. What do you think?

2023-04-14 15:44 UTC, labrocadabro commented on src/App.jsx
> +	}, [listToken, setListToken]);
Oh you're right! That was a leftover from some unneeded code that I removed.

2023-04-14 16:25 UTC, paramsiddharth requested changes
Almost everything looks good to me! Good work on the PR, Laura and Shagun! 😊 Just that one small change that Shah requested and your PR should be ready for approval.

2023-04-14 16:35 UTC, shahx95 commented on src/views/Home.jsx
> +	}, [token, navigate]);
I'm curious about why 'navigate' is included as a dependency for this 'useEffect'. Since 'navigate' is not expected to change after the component is mounted. As I understand, the intention is to trigger the 'useEffect' when a valid token is available and navigate to the list page.  Could you provide further clarification to help me better understand this approach?

2023-04-14 16:39 UTC, shahx95 commented on src/views/Home.jsx
> +	}, [token, navigate]);
The following approach would ensure that the 'useEffect' is triggered when the token transitions from null to a valid value, resulting in navigation to the list page. What are your thoughts on this?

 `useEffect(() => {
		if (token) navigate('/list');
	}, [token])`

2023-04-14 18:36 UTC, RajGM commented
Hi @labrocadabro and @shagunZ 
I am facing this error.
Would you like to try, or should I give some hints?

`$ git checkout la-sm-list-setup
Switched to branch 'la-sm-list-setup'
Your branch is up to date with 'origin/la-sm-list-setup'.
`

![error](https://user-images.githubusercontent.com/16620150/232128059-296e612c-a685-482c-9174-a652a0ef132c.jpg)

2023-04-15 01:16 UTC, labrocadabro commented
@RajGM  I *believe* that's due to the new package we added. Did you run `npm install`? (And I apologize, that should have been mentioned in the PR)

2023-04-15 01:39 UTC, RajGM commented
> @RajGM I _believe_ that's due to the new package we added. Did you run `npm install`? (And I apologize, that should have been mentioned in the PR)

Yes, I did npm install.

2023-04-15 02:08 UTC, RajGM commented
Good work, @labrocadabro and @shagunZ

2023-04-15 02:40 UTC, labrocadabro reviewed
Responding to @shahx95's comment about `navigate` in `useEffect`.  Removing it causes a React warning. Would like feedback from @paramsiddharth or @RajGM whether it's better to remove `navigate` and ignore the warning, or leave it in the dependency array.

2023-04-15 02:40 UTC, labrocadabro commented on src/views/Home.jsx
> +	}, [token, navigate]);
React gives us a warning when `navigate` is removed:

![React warning: navigate dependency missing](https://user-images.githubusercontent.com/5794319/232179048-91e65701-fc92-41ee-a0a4-05c803c0519e.png)

2023-04-15 04:29 UTC, RajGM commented on src/views/Home.jsx
> +	}, [token, navigate]);
move navigate() inside the useEffect to get rid of the warning.

2023-04-15 04:52 UTC, labrocadabro commented on src/views/Home.jsx
> +	}, [token, navigate]);
> move navigate inside the useEffect to get rid of the warning.

You mean like ```
	useEffect(() => {
		const navigate = useNavigate();
		if (token) navigate('/list');
	}, [token]);```?

That seems to break it completely:

![React error: can't use useNavigate inside useEffect](https://user-images.githubusercontent.com/5794319/232183713-79d8381e-1fc7-42f7-8413-ec5077979514.png)

Or did I misunderstand? Did you mean something else?

2023-04-15 06:25 UTC, RajGM commented on src/views/Home.jsx
> +	}, [token, navigate]);
Hi @labrocadabro 
Push the latest changes, I can have a look.

2023-04-15 06:30 UTC, labrocadabro commented on src/views/Home.jsx
> +	}, [token, navigate]);
Because the code errors, I can't commit it.

2023-04-15 06:31 UTC, paramsiddharth commented on src/views/Home.jsx
> +	}, [token, navigate]);
@labrocadabro We'll talk about it in the sync, don't worry! :) I believe it is a false positive.

2023-04-15 07:14 UTC, paramsiddharth commented
https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook
https://stackoverflow.com/questions/69626948/react-hook-useeffect-has-a-missing-dependency-dispatch-either-include-it-or

2023-04-15 07:31 UTC, paramsiddharth approved these changes
Excellent work, Shagun and Laura! <3 Let's merge the PR now!

2023-04-15 07:32 UTC, merged