Add task comment
the-collab-lab/tcl-60-smart-shopping-list pull request #17
Opened 2023-04-09 15:46 UTC by ToobaJamal

Co-authored-by: 24467345+shahx95@users.noreply.github.com

## Description

TBD

## Related Issue

Closes #4 

## Acceptance Criteria

- The Add Item view displays a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again. There should be 3 choices for this:
- “Soon”, corresponding to 7 days
- “Kind of soon”, corresponding to 14 days
- “Not soon”, corresponding to 30 days
- The input that accepts the name of the item has a semantic label element associated with it
- The user can submit this form with both the mouse and the Enter key
- When the user submits the form, they see a message indicating that the item either was or was not saved to the database.

### Data-related tasks:

- The console.log in the addItem function in src/api/firebase.js is replaced with a function that adds the new document to the Firestore database. That function will be imported from the firebase/firestore module.
- The user’s soon/not soon/kind of soon choice is used to calculate nextPurchasedDate

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![task4_before](https://user-images.githubusercontent.com/52610124/230782665-a06347f9-622a-4ffa-b62d-f608cb5a9f76.png)

### After

## Testing Steps / QA Criteria

TBD

2023-04-10 18:00 UTC, shahx95 commented on src/views/AddItem.jsx
> +				{submissionStatus === 'Form submitted' && (
May be we can refactor this as the following to read cleaner and be less redundant:

`setSubmissionStatus(
  formData.itemName && formData.daysUntilNextPurchase 
  ? 'Success! Item has been submitted'
  : 'Your submission was not successful. Please check your input and try again.'
);`

2023-04-10 18:08 UTC, shahx95 commented on src/views/AddItem.jsx
> +				{submissionStatus === 'Form submitted' && (
a better practice instead of using && for conditional rendering would be: 
`{submissionStatus === "form submitted" ? <p>Item has been added to list</p> : null}`

what do you think?

2023-04-10 18:20 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +				{submissionStatus === 'Form submitted' && (
I was saying the same 😬
I think I'll define another state to store a Boolean value indicating whether the message should be displayed or not and use that along with submissionStatus to display the respective message. The boolean state will be used in setTimeout to make the message disappear after a few seconds. How does it sound?

2023-04-10 18:22 UTC, shahx95 commented on src/views/AddItem.jsx
> +							id="7days"
I would prefer not to start the id with a number. Instead, I would opt to rewrite it using its corresponding word form, such as "sevenDays."

2023-04-10 18:31 UTC, shahx95 commented on src/views/AddItem.jsx
> +				{submissionStatus === 'Form submitted' && (
It sounds good. 😊 If it's not too much trouble, would you mind sharing your proposal here before our meeting tomorrow? This would enable us to concentrate on the database during our meeting. Atm I'm only reviewing for possible improvements that we can implement once the database operation is up and running.

2023-04-10 18:39 UTC, shahx95 commented on src/views/AddItem.jsx
> +		if (formData.itemName !== '' && formData.daysUntilNextPurchase !== '') {
Instead of using `if (formData.itemName !== '' && formData.daysUntilNextPurchase !== '')`, we could simplify the condition by utilizing truthiness, like so: `if (formData.itemName && formData.daysUntilNextPurchase)`. This approach considers any non-empty string input as valid for our purposes.

2023-04-10 18:47 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +		if (formData.itemName !== '' && formData.daysUntilNextPurchase !== '') {
I think we have another issue for this.

2023-04-10 19:28 UTC, shahx95 commented on src/views/AddItem.jsx
> +		if (formData.itemName !== '' && formData.daysUntilNextPurchase !== '') {
Ah ok. That's cool! 😊

2023-04-11 08:45 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +				{submissionStatus === 'Form submitted' && (
I am making the changes already, I'll push them and you can have a review. Sounds okay?

2023-04-11 14:32 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +		setTimeout(() => setShowMessage(false), 3000);
This issue can be solved by adding a bit of CSS but I think we are not required to deal with the styling yet.

2023-04-11 15:07 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +		setTimeout(() => setShowMessage(false), 3000);
I am also thinking about clearing the form when the user hits the submit button

2023-04-11 15:33 UTC, shahx95 commented on src/views/AddItem.jsx
> +		setTimeout(() => setShowMessage(false), 3000);
Yeah we should do that

2023-04-12 14:14 UTC, shahx95 commented
As per your previous suggestion, I implemented the form clearance feature after submission. I also added retrieval of data from local storage. Kindly review the changes made accordingly.

2023-04-13 13:23 UTC, labrocadabro approved these changes
Looks good! I do have a few comments, but nothing that would prevent merging.

1) If you move the confirmation message below the submit button, then you won't need to worry about the button shifting anymore. I think that's the more common position anyway.

2) I'm not a fan of error messages that automatically disappear. If the user misses it, they won't have any idea why their submission didn't go through & might even think that it did. This can lead to frustration.

3) For accessibility purposes, you might want to look into `aria-live` for the text that appears and disappears: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

2023-04-13 17:41 UTC, shagunZ approved these changes
Everything looks good to me!!

2023-04-14 09:44 UTC, ToobaJamal commented
> Looks good! I do have a few comments, but nothing that would prevent merging.
> 
> 1. If you move the confirmation message below the submit button, then you won't need to worry about the button shifting anymore. I think that's the more common position anyway.
> 2. I'm not a fan of error messages that automatically disappear. If the user misses it, they won't have any idea why their submission didn't go through & might even think that it did. This can lead to frustration.
> 3. For accessibility purposes, you might want to look into `aria-live` for the text that appears and disappears: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

Thank you for adding these points, Laura. These are helpful :)

2023-04-14 16:17 UTC, shahx95 commented
@labrocadabro thanks for the feedback. 

> 1. If you move the confirmation message below the submit button, then you won't need to worry about the button shifting anymore. I think that's the more common position anyway.
> 2. I'm not a fan of error messages that automatically disappear. If the user misses it, they won't have any idea why their submission didn't go through & might even think that it did. This can lead to frustration.

I am not convinced with the current placement and user experience of the error message as it is right now. @ToobaJamal has mentioned that this can be addressed during the styling phase, so we may consider it a minor issue for now and come back to it later. @paramsiddharth, I would appreciate your opinion on this matter as well.

2023-04-14 16:32 UTC, paramsiddharth commented on src/views/AddItem.jsx
> +					daysUntilNextPurchase: Number(formData.daysUntilNextPurchase),
Is it better to use `Number(str)` than `parseInt(str)`? There's no right answer, so I'll let you discover and decide on your own! 😃 Here's something you might want to check out: https://stackoverflow.com/questions/4090518/what-is-the-difference-between-parseint-and-number

2023-04-14 16:33 UTC, paramsiddharth commented on src/views/AddItem.jsx
> +import React from 'react';
A part of the suggestion for my next comment.

```suggestion
import React, { useState } from 'react';
```

2023-04-14 16:34 UTC, paramsiddharth commented on src/views/AddItem.jsx
> +	const [showMessage, setShowMessage] = React.useState(false);
If we're using the `useState` hook so many times, wouldn't it be a better idea to just import it instead of writing `React.useState` everytime? :) Think about it, it is always encouraged to do this in production code. If you're using a property more than 3 times and it is possible to import it selectively, the key is to do that.

```suggestion
	const [formData, setFormData] = useState({
		itemName: '',
		daysUntilNextPurchase: '',
	});
	const [submissionStatus, setSubmissionStatus] = useState('');
	const [showMessage, setShowMessage] = useState(false);
```

2023-04-14 16:36 UTC, paramsiddharth commented on src/views/AddItem.jsx
> +	}
I admire how you two wrote a generic function that would work for any field. 🌷 Impressive!

2023-04-14 16:38 UTC, paramsiddharth requested changes
A few changes are needed, and then you'll be good to go! :) Excellent and quality work on the PR, Shah and Tooba!

2023-04-14 18:28 UTC, RajGM commented
@shahx95 absorbs office hour insight and PR feedback very quickly.
LGTM.

2023-04-14 18:28 UTC, RajGM approved these changes
LGTM

2023-04-15 03:59 UTC, labrocadabro commented
> @labrocadabro thanks for the feedback.
> 
> > 1. If you move the confirmation message below the submit button, then you won't need to worry about the button shifting anymore. I think that's the more common position anyway.
> > 2. I'm not a fan of error messages that automatically disappear. If the user misses it, they won't have any idea why their submission didn't go through & might even think that it did. This can lead to frustration.
> 
> I am also not entirely convinced by the current placement and user experience of the error message as it is currently. As mentioned by @ToobaJamal, we could potentially address this during the styling phase, so we may consider it a minor issue for now and revisit it later. @paramsiddharth, I would appreciate your opinion on this matter as well.

@shahx95 This is why I asked on slack if we should be addressing UI/UX concerns as we go. I'm unclear on whether such issues are scope creep, or if they're supposed to be addressed but are up to the discretion of the authors and therefore difficult to put in the acceptance criteria.

Would appreciate it if @paramsiddharth, @RajGM, or @iamkrati22 could weigh in.

2023-04-15 06:10 UTC, ToobaJamal commented on src/views/AddItem.jsx
> +	const [showMessage, setShowMessage] = React.useState(false);
I have made the requested changes :)

2023-04-15 06:36 UTC, paramsiddharth approved these changes
Excellent work, Tooba and Shah! <3 Looks good to me!

2023-04-15 07:52 UTC, paramsiddharth approved these changes
Excellent job, Tooba and Shah! <3 I'm impressed. Let's merge it now!

2023-04-15 07:52 UTC, merged