Add task comment
the-collab-lab/tcl-60-smart-shopping-list pull request #19
Opened 2023-04-16 12:28 UTC by shagunZ

Co-authored-by: ToobaJamal [https://github.com/ToobaJamal](https://github.com/ToobaJamal)

## Description

## Related Issue

Closes https://github.com/the-collab-lab/tcl-60-smart-shopping-list/issues/5

## Acceptance Criteria

If a user doesn’t already have a token:

- [ ]  The Home view shows a form that allows the user to enter a token to join an existing list, in addition to the button that allows them to create a new list.

- [ ]  The input that accepts the list token has a semantic label element associated with its

- [ ]  The user can submit this form with both the mouse and the Enter key

- [ ]  If the list exists,

- the token is saved in localStorage

- the user is redirected to the List view and shown the items on that list

- [ ]  If the list does not exist, the user is shown an error message that explains the problem

If a user does already have a token:

- [ ]  They are automatically redirected to the List view.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2023-04-21 03:51 UTC, labrocadabro requested changes
Just one thing I think should be changed:

Currently if I want to share my list with someone else, there's no way for me to get the token except to use the dev tools to find it in localStorage. Most users wouldn't know how to do that, so I think the current token should be displayed on the /list page, with a message like "To share this list use the following token:".

2023-04-23 04:42 UTC, paramsiddharth commented on src/views/Home.css
> +}
Point to note: In future we'll need to scope these styles as well as apply some finishing!

2023-04-23 04:44 UTC, paramsiddharth approved these changes
Impressive. Tooba and Shagun! :) Good work!

Although what Laura said makes a lot of sense, the PR passes the acceptance criteria, so I'll be happy to merge this in. If you'd like to make the update Laura suggested, feel free to do that before we merge it in today's sync.

2023-04-23 07:14 UTC, RajGM commented
Good work.
 Tooba and Shagun!

2023-04-23 07:24 UTC, paramsiddharth approved these changes

2023-04-23 07:25 UTC, merged